# Generated by Django 6.0.5 on 2026-05-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(choices=[('combina', 'Combina'), ('especial', 'Especial'), ('desayuno', 'Desayuno'), ('bocadillos', 'Bocadillos'), ('cafes', 'Cafés')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=50)),
                ('emoji', models.CharField(default='🍱', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
